name: py312-local

channels:
  - conda-forge

dependencies:
  - python=3.12
  - pip
  - pip:
    - ipykernel==6.29.5
    - numpy==2.1.3
    - nvidia-cublas-cu12==12.4.5.8
    - nvidia-cuda-cupti-cu12==12.4.127
    - nvidia-cuda-nvrtc-cu12==12.4.127
    - nvidia-cuda-runtime-cu12==12.4.127
    - nvidia-cudnn-cu12==9.1.0.70
    - nvidia-cufft-cu12==11.2.1.3
    - nvidia-curand-cu12==10.3.5.147
    - nvidia-cusolver-cu12==11.6.1.9
    - nvidia-cusparse-cu12==12.3.1.170
    - nvidia-nccl-cu12==2.21.5
    - nvidia-nvjitlink-cu12==12.4.127
    - nvidia-nvtx-cu12==12.4.127
    - torch==2.5.1
    - torchaudio==2.5.1
    - torchvision==0.20.1
    - matplotlib
    - typing_extensions
    - pytest