[project]
name = "MQGeometry"
version = "1.0.0"
description = ""
authors = [{name="Louis Thiry"}]
readme = "README.md"
requires-python = ">=3.9"


[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
